#!/bin/bash

iptables=/sbin/iptables

interface=$(ip link | awk -F: '$0 !~ "lo|vir|wl|^[^0-9]"{print $2;getline}')

$iptables -P INPUT DROP

$iptables -A INPUT -i $interface -s 0.0.0.0/0 -p all -m state --state ESTABLISHED,RELATED -j ACCEPT

$iptables -A INPUT -s $1 -i $interface -p tcp --dport 80 -j ACCEPT

$iptables -A INPUT -s $1 -i $interface -p tcp --dport 22 -j ACCEPT

$iptables -A INPUT -s $1 -i $interface -p tcp --dport 10050 -j ACCEPT

$iptables -A INPUT -s $1 -i $interface -p tcp --dport 10051 -j ACCEPT

iptables-save > /etc/iptables/rules.v4
