#!/bin/bash

iptables=/sbin/iptables

interface=$(ip link | awk -F: '$0 !~ "lo|vir|wl|^[^0-9]"{print $2;getline}')

$iptables -P INPUT DROP

$iptables -A INPUT -s $1 -i $interface -p tcp --dport 80 -j ACCEPT

$iptables -A INPUT -s $1 -i $interface -p tcp --dport 22 -j ACCEPT

dpkg-reconfigure iptables-persistent
